import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'

const STORE_INFO = {
  name: "NovaMart",
  address: "21 MG Road, Tilakwadi, Belagavi, Karnataka, India - 590006",
  phone: "+91 98765 43210",
  email: "support@novamart.store",
};


const currency = new Intl.NumberFormat('en-IN', {
  style: 'currency',
  currency: 'INR'
})

export function downloadPurchaseOrderPdf(order) {
  if (!order) {
    throw new Error('No order data provided for PDF export')
  }

  const doc = new jsPDF()

  // Header
  doc.setFontSize(18)
  doc.text(STORE_INFO.name, 14, 18)
  doc.setFontSize(10)
  doc.text(STORE_INFO.address, 14, 24)
  doc.text(`Phone: ${STORE_INFO.phone}`, 14, 30)
  doc.text(`Email: ${STORE_INFO.email}`, 14, 36)

  doc.setFontSize(16)
  doc.text('Purchase Order', 150, 18)

  doc.setFontSize(11)
  const createdDate = order.order_date || order.created_at
  doc.text(`PO Number: ${order.order_number}`, 150, 26)
  if (createdDate) {
    doc.text(`Order Date: ${new Date(createdDate).toLocaleDateString()}`, 150, 32)
  }
  if (order.expected_delivery) {
    doc.text(`Expected Delivery: ${new Date(order.expected_delivery).toLocaleDateString()}`, 150, 38)
  }

  // Supplier info
  doc.setFontSize(12)
  doc.text('Supplier Details', 14, 50)
  doc.setFontSize(10)
  doc.text(order.supplier?.name || 'Supplier: N/A', 14, 56)
  if (order.supplier?.contact_person) doc.text(`Contact: ${order.supplier.contact_person}`, 14, 62)
  if (order.supplier?.email) doc.text(`Email: ${order.supplier.email}`, 14, 68)
  if (order.supplier?.phone) doc.text(`Phone: ${order.supplier.phone}`, 14, 74)

  const items = order.items || []

  autoTable(doc, {
    startY: 82,
    head: [['Item', 'Quantity', 'Unit Price', 'Line Total']],
    body: items.length
      ? items.map((item) => [
          item.product_name || 'Unnamed item',
          item.quantity || 0,
          currency.format(item.unit_price || 0),
          currency.format((item.quantity || 0) * (item.unit_price || 0))
        ])
      : [['No items found', '-', '-', '-']],
    styles: { fontSize: 10 },
    headStyles: { fillColor: [99, 102, 241] }
  })

  const tableBottom = doc.lastAutoTable.finalY || 100
  const totalValue =
    order.total_value ||
    items.reduce((sum, item) => sum + (item.quantity || 0) * (item.unit_price || 0), 0)

  doc.setFontSize(11)
  doc.text(`Total Items: ${order.items_count ?? items.length}`, 14, tableBottom + 10)
  doc.text(`Total Amount: ${currency.format(totalValue)}`, 14, tableBottom + 18)

  if (order.notes) {
    doc.text('Notes:', 14, tableBottom + 28)
    doc.setFontSize(10)
    const splitNotes = doc.splitTextToSize(order.notes, 180)
    doc.text(splitNotes, 14, tableBottom + 34)
  }

  doc.setFontSize(9)
  doc.setTextColor(120)
  doc.text('Generated by NovaMart Smart Inventory Manager', 14, 285)

  doc.save(`${order.order_number || 'purchase-order'}.pdf`)
}
